/**
 * Translations for german Language
 * (needs to be loaded after functions.js)
 */

Lang.setStrings({
    'RTR-NetTest': 'RTR-Netztest',
    'Mbps' : 'Mbit/s',
    'ms' : 'ms',
    'dBm' : 'dBm',
    'dB' : 'dB',
    'East' : 'O',
    'West' : 'W',
    'North' : 'N',
    'South' : 'S',
    'showMoreDevices' : 'Weitere Geräte',
    'AndroidAppAvailable' : 'Falls Sie den Test in vollem Umfang durchführen wollen, verwenden Sie bitte unsere <a href="https://play.google.com/store/apps/details?id=at.alladin.rmbt.android&hl=de">Android-App</a>.</p>',
    'IOSAppAvailable' : 'Falls Sie den Test in vollem Umfang durchführen wollen, verwenden Sie bitte unsere <a href="https://itunes.apple.com/at/app/rtr-netztest/id724321403">iOS-App</a>.</p>',
    'NoJavaAvailable' : 'Ein einfacher JavaScript-Test wird durchgeführt.',
    'BrowserOutdated' : 'Ihr Browser ist zu alt und unterstützt nicht alle Funktionen, die zur Durchführung des Tests notwendig wären. Bitte verwenden Sie einen neueren oder anderen Browser.',
    'YourPostalCode' : 'Ihre Postleitzahl',
    'PostalCode' : 'Postleitzahl',
    'PleaseEnterPostalCode' : 'Bitte geben Sie für ein bestmögliches Ergebnis Ihre Postleitzahl an.',
    'OutsideAustria' : 'Ausland',
    'StreetAddress' : 'Straße/Nr.',
    'Country' : 'Land',
    'City' : 'Ort',
    'AddressInput' : 'Optionale, manuelle Adresseingabe',
    'PrivacyStatement' : 'Datenschutzbestimmungen',
    'PrivacyStatementLink' : 'https://www.rtr.at/de/tk/netztestprivacypolicy',
    'AustrianPostalCode' : 'Österr. Postleitzahl',
    'gkz' : 'Gemeindekennzahl',
    'community': 'Gemeinde',
    'locality': 'Katastralgemeinde',
    'district' : 'Bezirk',
    'province' : 'Bundesland',
    'Cancel' : 'Abbrechen',
    'Continue' : 'Weiter',
    'clickToEdit' : 'zum Ändern anklicken',
    'MeasurementResultFrom' : 'Messergebnis vom',
    'TestResult' : 'Testergebnis',
    'YourSyncCode' : 'Ihr Synchronisations-Code lautet',
    'History' : 'Verlauf',
    'allOperators' : 'alle Betreiber',
    'countries' : {'eu' : 'Europa', 'af': 'Afghanistan', 'eg': 'Ägypten', 'al' : 'Albanien', 'dz': 'Algerien' , 'as': 'Amerikanisch-Samoa', 'vi': 'Amerikanische Jungferninseln', 'ad': 'Andorra', 'ao': 'Angola', 'ai': 'Anguilla', 'aq': 'Antarktika', 'ag': 'Antigua und Barbuda', 'gq': 'Äquatorialguinea', 'ar': 'Argentinien', 'am': 'Armenien', 'aw': 'Aruba', 'az': 'Aserbaidschan', 'et': 'Äthiopien', 'au': 'Australien', 'bs': 'Bahamas', 'bh': 'Bahrain', 'bd': 'Bangladesch', 'bb': 'Barbados', 'by': 'Belarus (Weißrussland)', 'be': 'Belgien', 'bz': 'Belize', 'bj': 'Benin', 'bm': 'Bermuda', 'bt': 'Bhutan', 'bo': 'Bolivien', 'bq': 'Bonaire, Sint Eustatius und Saba (Niederlande)', 'ba': 'Bosnien und Herzegowina', 'bw': 'Botswana', 'bv': 'Bouvetinsel', 'br': 'Brasilien', 'vg': 'Britische Jungferninseln', 'io': 'Britisches Territorium im Indischen Ozean', 'bn': 'Brunei Darussalam', 'bg': 'Bulgarien', 'bf': 'Burkina Faso', 'bi': 'Burundi', 'cl': 'Chile', 'cn': 'China, Volksrepublik', 'ck': 'Cookinseln', 'cr': 'Costa Rica', 'ci': 'Côte d’Ivoire (Elfenbeinküste)', 'cw': 'Curaçao', 'dk': 'Dänemark', 'de': 'Deutschland', 'dm': 'Dominica', 'do': 'Dominikanische Republik', 'dj': 'Dschibuti', 'ec': 'Ecuador', 'sv': 'El Salvador', 'er': 'Eritrea', 'ee': 'Estland', 'fk': 'Falklandinseln', 'fo': 'Färöer', 'fj': 'Fidschi', 'fi': 'Finnland', 'fr': 'Frankreich', 'gf': 'Französisch-Guayana', 'pf': 'Französisch-Polynesien', 'tf': 'Französische Süd- und Antarktisgebiete', 'ga': 'Gabun', 'gm': 'Gambia', 'ge': 'Georgien', 'gh': 'Ghana', 'gi': 'Gibraltar', 'gd': 'Grenada', 'gr': 'Griechenland', 'gl': 'Grönland', 'gp': 'Guadeloupe', 'gu': 'Guam', 'gt': 'Guatemala', 'gg': 'Guernsey (Kanalinsel)', 'gn': 'Guinea', 'gw': 'Guinea-Bissau', 'gy': 'Guyana', 'ht': 'Haiti', 'hm': 'Heard und McDonaldinseln', 'hn': 'Honduras', 'hk': 'Hongkong', 'in': 'Indien', 'id': 'Indonesien', 'im': 'Insel Man', 'iq': 'Irak', 'ir': 'Iran, Islamische Republik', 'ie': 'Irland', 'is': 'Island', 'il': 'Israel', 'it': 'Italien', 'jm': 'Jamaika', 'jp': 'Japan', 'ye': 'Jemen', 'je': 'Jersey (Kanalinsel)', 'jo': 'Jordanien', 'yu': 'Jugoslawien (ehemalig)', 'ky': 'Kaimaninseln', 'kh': 'Kambodscha', 'cm': 'Kamerun', 'ca': 'Kanada', 'cv': 'Kap Verde', 'kz': 'Kasachstan', 'qa': 'Katar', 'ke': 'Kenia', 'kg': 'Kirgisistan', 'ki': 'Kiribati', 'cc': 'Kokosinseln', 'co': 'Kolumbien', 'km': 'Komoren', 'cd': 'Kongo, Demokratische Republik (ehem. Zaire)', 'cg': 'Republik Kongo', 'kp': 'Korea, Demokratische Volksrepublik (Nordkorea)', 'kr': 'Korea, Republik (Südkorea)', 'hr': 'Kroatien', 'cu': 'Kuba', 'kw': 'Kuwait', 'la': 'Laos, Demokratische Volksrepublik', 'ls': 'Lesotho', 'lv': 'Lettland', 'lb': 'Libanon', 'lr': 'Liberia', 'ly': 'Libyen', 'li': 'Liechtenstein', 'lt': 'Litauen', 'lu': 'Luxemburg', 'mo': 'Macao', 'mg': 'Madagaskar', 'mw': 'Malawi', 'my': 'Malaysia', 'mv': 'Malediven', 'ml': 'Mali', 'mt': 'Malta', 'ma': 'Marokko', 'mh': 'Marshallinseln', 'mq': 'Martinique', 'mr': 'Mauretanien', 'mu': 'Mauritius', 'yt': 'Mayotte', 'mk': 'Mazedonien', 'mx': 'Mexiko', 'fm': 'Mikronesien', 'md': 'Moldawien (Republik Moldau)', 'mc': 'Monaco', 'mn': 'Mongolei', 'me': 'Montenegro', 'ms': 'Montserrat', 'mz': 'Mosambik', 'mm': 'Myanmar (Burma)', 'na': 'Namibia', 'nr': 'Nauru', 'np': 'Nepal', 'nc': 'Neukaledonien', 'nz': 'Neuseeland', 'ni': 'Nicaragua', 'nl': 'Niederlande', 'an': 'Niederländische Antillen (ehemalig)', 'ne': 'Niger', 'ng': 'Nigeria', 'nu': 'Niue', 'mp': 'Nördliche Marianen', 'nf': 'Norfolkinsel', 'no': 'Norwegen', 'om': 'Oman', 'at': 'Österreich', 'tl': 'Osttimor (Timor-Leste)', 'pk': 'Pakistan', 'ps': 'Staat Palästina', 'pw': 'Palau', 'pa': 'Panama', 'pg': 'Papua-Neuguinea', 'py': 'Paraguay', 'pe': 'Peru', 'ph': 'Philippinen', 'pn': 'Pitcairninseln', 'pl': 'Polen', 'pt': 'Portugal', 'pr': 'Puerto Rico', 're': 'Réunion', 'rw': 'Ruanda', 'ro': 'Rumänien', 'ru': 'Russische Föderation', 'sb': 'Salomonen', 'bl': 'Saint-Barthélemy', 'mf': 'Saint-Martin (franz. Teil)', 'zm': 'Sambia', 'ws': 'Samoa', 'sm': 'San Marino', 'st': 'São Tomé und Príncipe', 'sa': 'Saudi-Arabien', 'se': 'Schweden', 'ch': 'Schweiz (Confoederatio Helvetica)', 'sn': 'Senegal', 'rs': 'Serbien', 'sc': 'Seychellen', 'sl': 'Sierra Leone', 'zw': 'Simbabwe', 'sg': 'Singapur', 'sx': 'Sint Maarten (niederl. Teil)', 'sk': 'Slowakei', 'si': 'Slowenien', 'so': 'Somalia', 'es': 'Spanien', 'lk': 'Sri Lanka', 'sh': 'St. Helena', 'kn': 'St. Kitts und Nevis', 'lc': 'St. Lucia', 'pm': 'Saint-Pierre und Miquelon', 'vc': 'St. Vincent und die Grenadinen', 'za': 'Südafrika', 'sd': 'Sudan', 'gs': 'Südgeorgien und die Südlichen Sandwichinseln', 'ss': 'Südsudan', 'sr': 'Suriname', 'sj': 'Svalbard und Jan Mayen', 'sz': 'Swasiland', 'sy': 'Syrien, Arabische Republik', 'tj': 'Tadschikistan', 'tw': 'Republik China (Taiwan)', 'tz': 'Tansania, Vereinigte Republik', 'th': 'Thailand', 'tg': 'Togo', 'tk': 'Tokelau', 'to': 'Tonga', 'tt': 'Trinidad und Tobago', 'td': 'Tschad', 'cz': 'Tschechische Republik','tn': 'Tunesien', 'tr': 'Türkei', 'tm': 'Turkmenistan', 'tc': 'Turks- und Caicosinseln', 'tv': 'Tuvalu', 'ug': 'Uganda', 'ua': 'Ukraine', 'hu': 'Ungarn', 'um': 'United States Minor Outlying Islands', 'uy': 'Uruguay', 'uz': 'Usbekistan', 'vu': 'Vanuatu', 'va': 'Vatikanstadt', 've': 'Venezuela', 'ae': 'Vereinigte Arabische Emirate', 'us': 'Vereinigte Staaten von Amerika', 'gb': 'Vereinigtes Königreich Großbritannien und Nordirland', 'vn': 'Vietnam', 'wf': 'Wallis und Futuna', 'cx': 'Weihnachtsinsel', 'eh': 'Westsahara', 'cf': 'Zentralafrikanische Republik', 'cy': 'Zypern'},
    'invalidUUID' : 'Ungültige UUID',
    'decimalSeperator'   : ',',
    'thousandsSeperator' : '.',
    'implausibleResult' : 'Anmerkung: Implausibles Testergebnis, Test wird ignoriert.',
    'NDTTestFailed' : 'NDT-Test fehlgeschlagen!',
    'NDTTestFinished' : 'NDT-Test abgeschlossen!',
    'CourseOverview' : 'Verlauf',
    'seconds_abbreviation' : 's',
    'meters_abbreviation' : 'm',
    'showAdditionalInformation' : 'Mehr Informationen anzeigen ...',
    'Measurement' : 'Messung',
    'Net' : 'Netz',
    'moreInfo' : 'Mehr Infos',
    'smallView' : 'kleine Ansicht',
    'largeView' : 'große Ansicht',
    'baseLayer' : 'Kartentyp',
    'Skip' : 'Überspringen',
    'basemap_bmapgrau' : 'Basemap.at - Grau',
    'basemap_geolandbasemap' : 'Basemap.at - Standard',
    'basemap_bmaphidpi' : 'Basemap.at - High DPI',
    'basemap_bmaporthofoto30cm' : 'Basemap.at - Luftbild',
    'map_dateformat' : 'DD.MM.YYYY HH:mm:ss', //http://momentjs.com/docs/#/displaying/
    'map_index_dateformat' : 'HH:mm:ss',
    'all' : 'Alle',

    //fields from controlserver-resource
    'time': 'Testzeitpunkt',
    'timezone': 'Zeitzone',
    'ping_shortest': 'Ping',
    'speed_upload': 'Upload',
    'speed_download': 'Download',
    'signal_strength': 'Signalstärke',
    'network_type': 'Netztyp',
    'zip_code': 'PLZ',
    'country_location': 'Land Standort',
    'country_asn': 'Land des AS',
    'country_geoip': 'Land der IP',
    'wifi_ssid': 'WLAN-SSID',
    'wifi_bssid': 'WLAN-BSSID',
    'network_operator_name': 'Netz (Anzeige)',
    'network_name': 'Netz (Anzeige)',
    'network_operator': 'Mobilfunknetz',
    'network_sim_operator_name': 'Heimatnetz (Anzeige)',
    'network_sim_operator': 'Heimatnetz',
    'roaming': 'Roaming',
    'total_bytes': 'Datenvolumen RMB-Test',
    'total_if_bytes': 'Datenvolumen Interface',
    'test_if_bytes_download': 'Daten If_Dl',
    'test_if_bytes_upload': 'Daten If_Ul',
    'testdl_if_bytes_download': 'Daten If_Dl (Dl-Test)',
    'testdl_if_bytes_upload': 'Daten If_Ul (Dl-Test)',
    'testul_if_bytes_download': 'Daten If_Dl (Dl-test)',
    'testul_if_bytes_upload': 'Daten If_Ul (Ul-Test)',
    'client_name': 'Softwarebezeichnung',
    'client_type': 'RMBT-Typ',
    'client_version': 'RMBT-Version',
    'client_software_version': 'Software-Version',
    'plattform': 'Plattform',
    'os_version': 'Plattform-Version',
    'model': 'Modell',
    'client_local_ip': 'Interne IP ',
    'client_public_ip': 'Externe IP',
    'client_public_ip_as_name': 'Name des IP-Netzwerks',
    'client_public_ip_as': 'IP-Netzwerk (Name des AS)',
    'client_public_ip_rdns': 'Hostname',
    'provider_name': 'Betreiber',
    'nat_type': 'NAT-Status',
    'location': 'Standort',
    'motion': 'Bewegung',
    'server_name': 'Name Testserver',
    'server_ip': 'IP Testserver',
    'server_location_name': 'Standort Testserver',
    'port': 'Port Testserver',
    'encryption': 'RMBT-Verschlüsselung',
    'encryption_false': 'Nein',
    'encryption_true': 'Ja',
    'duration': 'Testdauer',
    'num_threads': 'Parallele Verbindungen DL',
    'num_threads_ul': 'Parallel Verbindungen UL',
    'uuid': 'Test-ID',
    'open_test_uuid': 'Open-Test-ID',
    'speed_download_ndt': 'Download (NDT)',
    'speed_upload_ndt': 'Upload (NDT)',
    'ping_ndt': 'Latenz (NDT)',
    'ndt_details_main': 'Details NDT (main)',
    'ndt_details_stat': 'Details NDT (stat)',
    'ndt_details_diag': 'Details NDT (diag)',
    'speed': 'Geschwindigkeit',
    'bearing': 'Richtung',
    'altitude': 'Seehöhe',
    'timing_advance': 'Timing Advance',

    //values not in the controlserver resource file
    'cat_technology' : 'Verbindungstechnologie',
    'country_sim' : 'SIM-Heimatland',
    'platform' : 'Plattform',
    'ip_anonym' : 'IP (anonymisiert)',
    'open_uuid' : 'Open-User-UUID',
    'network_country' : 'Land des Netzwerks',
    'distance' : 'Zurückgelegter Weg',
    'lte_rsrp' : 'Signalstärke (RSRP)',
    'lte_rsrq' : 'Signalqualität (RSRQ)',
    'referenced_signal_received_quality': 'Reference Signal Received Quality',


    'model_native': 'Modell (Original)',
    'ndt_download_kbit': 'NDT-Datenrate Download',
    'ndt_upload_kbit': 'NDT-Datenrate Upload',
    'time_dl_ms': 'Rel. Startzeitpunkt Download',
    'time_ul_ms': 'Rel. Startzeitpunkt Upload',
    'roaming_type': 'Roaming-Status',
    'wifi_link_speed': 'WLAN-Geschwindigkeit',
    'asn': 'AS-Nummer',
    'num_threads_requested': 'Anzahl angef. Verbindungen',
    'sim_mcc_mnc': 'Heimatnetz MCC-MNC',
    'duration_download_ms': 'Downloaddauer',
    'duration_upload_ms': 'Uploaddauer',
    'network_mcc_mnc': 'Mobilfunknetz MCC-MNC',
    'bytes_download': 'Datenmenge Download',
    'bytes_upload': 'Datenmenge Upload',
    'bytes': 'Bytes',
    'KB': 'KB',
    'MB': 'MB',
    'public_ip_as_name': 'Name des IP-Netzwerks',

    'roaming_international': 'internationales Roaming',
    'roaming_national': 'nationales Roaming',
    'roaming_none': 'kein Roaming',

    'pleaseSelect' : 'Bitte auswählen',
    'addressNotFound' : 'Ort konnte nicht gefunden werden',

    //Test
    'Locating': 'Ortung',
    'Initializing' : 'Initialisierung',
    'WaitForSlot' : 'Warte auf Server',
    'Init_Upload' : 'Init Upload',
    'Ping' : 'Ping',
    'Download' : 'Download',
    'Upload' : 'Upload',
    'Down': 'Down',
    'Up': 'Up',
    'Mio_abbr': 'Mio',
    'Thou_abbr': 'Tsd',
    'Finished' : 'Beendet',
    'Error' : 'Fehler',
    'Aborted' : 'Abgebrochen',
    'ErrorOccuredDuringTest' : 'Während des Tests ist ein Fehler aufgetreten.<br />Bitte starten Sie den Test erneut.',
    'PrematureEnd' : 'Der Tests wurde vorzeitig beendet.<br />Bitte starten Sie den Test erneut.',
    'AppletCouldNotBeLoaded' : 'Das Java-Applet konnte nicht gestartet werden.<br /> Bitte überprüfen Sie Ihre Java-Installation unter: <a href="http://www.java.com/de/download/testjava.jsp">http://www.java.com/de/download/testjava.jsp</a>',
    'ErrorOnInitializingApplet' : 'Fehler beim Intialisieren des Test-Applets',
    'VerlaufHash' : '/de/Verlauf#',
    'Init_applet' : 'Init Applet',
    'NoPermission'  : 'Keine Berechtigung',
    'NotAvailable' : 'Nicht verfügbar',
    'NotSupported' : 'Not supported',
    'DownloadPhase' : 'Download-Phase',
    'UploadPhase' : 'Upload-Phase',
    'Successful' : 'Erfolgreich',
    'NDT' : 'NDT',
    'Failure' : 'Fehlgeschlagen',
    'details' : 'Details',
    'NoOperatorsFound' : 'Keine Provider verfügbar in der aktuellen Filterung',
    'NoDevicesFound' : 'Keine Geräte verfügbar in der aktuellen Filterung',
    'QosTest' : 'Quality of Service',
    'FastConnectionWarning' : 'Aufgrund des verwendeten Testtyps kann es bei Ihrer schnellen Internetanbindung zu technisch bedingten Messschwankungen kommen. Vermuten Sie, dass die Ergebnisse nicht die tatsächliche Leistung widerspiegeln, führen Sie bitte einen Test mit der <a href="https://www.rtr.at/de/tk/rtrnetztest_tests">Android/iOS-App</a> durch.',
    'CheckConnection': "Bitte überprüfen Sie ihre Internetverbindung",
    'TestsInTheLastXHours' : 'Tests in den letzten % Stunden',
    'TestsInTheLastXMinutes' : 'Tests in den letzten % Minuten',
    'NoUUID' : 'Keine UUID vorhanden',
    'SafariBroken' : 'Bitte verwenden Sie für die Durchführung des Netztests <a href="https://www.mozilla.org/de/firefox/new/">Mozilla Firefox</a> oder <a href="https://www.google.de/chrome/browser/desktop/">Google Chrome</a>. Weitere Informationen dazu finden Sie <a href="https://www.rtr.at/de/tk/netztestfaq_web_100">in den FAQ</a>.',
    'LoopMode' : 'Wiederholungsmodus',
    'LoopModeTestsFinished' : 'Alle Tests abgeschlossen',
    'LoopModeFinished' : 'Serie beendet',
    'WaitingForStart' : 'Warte auf Zeitablauf',
    'radio_band': 'Frequenzband',
    'channel_number': 'Frequenzkanal',
    'DontAskAgain': 'Nicht erneut nachfragen',
    'CancelTest': 'Laufenden Test abbrechen?',

    //corine land covers
    'corine_100':'Bebaute Fläche',
    'corine_110':'Städtisch geprägte Flächen',
    'corine_111':'durchgängig städtische Prägung',
    'corine_112':'nicht durchgängig städtische Prägung',
    'corine_120':'Industrie-, Gewerbe- und Verkehrsflächen',
    'corine_121':'Industrie/Gewerbeflächen',
    'corine_122':'Straßen/Eisenbahnnetze, funktionell zugeordnete Flächen',
    'corine_123':'Hafengebiete',
    'corine_124':'Flughäfen',
    'corine_130':'Abbauflächen, Deponien, Baustellen',
    'corine_131':'Abbauflächen',
    'corine_132':'Deponien, Abraumhalden',
    'corine_133':'Baustellen',
    'corine_140':'Künstlich angelegte nicht landwirtschaftlich genutzte Flächen',
    'corine_141':'Städtische Grünflächen',
    'corine_142':'Sport/Freizeitanlagen',
    'corine_200':'Landwirtschaft',
    'corine_210':'Ackerflächen',
    'corine_211':'Nicht bewässertes Ackerland',
    'corine_212':'Regelmäßig bewässertes Ackerland',
    'corine_213':'Reisfelder',
    'corine_220':'Dauerkulturen',
    'corine_221':'Weinbauflächen',
    'corine_222':'Obst/Beerenobstbestände',
    'corine_223':'Olivenhaine',
    'corine_230':'Grünland',
    'corine_231':'Wiesen und Weiden',
    'corine_240':'Heterogene landwirtschaftliche Flächen',
    'corine_241':'Einjähr. Kulturen in Verbindung mit Dauerkulturen',
    'corine_242':'Komplexe Parzellenstruktur',
    'corine_243':'Landwirtschaftlich genutztes Land mit Flächen natürlicher Vegetation von signifikanter Größe',
    'corine_244':'Land/Forstwirtschaftliche Flächen',
    'corine_300':'Wälder und naturnahe Flächen',
    'corine_310':'Wälder',
    'corine_311':'Laubwälder',
    'corine_312':'Nadelwälder',
    'corine_313':'Mischwälder',
    'corine_320':'Kraut/Strauchvegetation',
    'corine_321':'Natürliches Grünland',
    'corine_322':'Heiden und Moorheiden',
    'corine_323':'Hartlaubbewuchs',
    'corine_324':'Wald/Strauch Übergangsstadien',
    'corine_330':'Offene Flächen ohne oder mit geringer Vegetation',
    'corine_331':'Strände, Dünen, Sandflächen',
    'corine_332':'Felsflächen ohne Vegetation',
    'corine_333':'Flächen mit spärlicher Vegetation',
    'corine_334':'Brandflächen',
    'corine_335':'Gletscher/Dauerschneegebiet',
    'corine_400':'Feuchtflächen',
    'corine_410':'Feuchtflächen im Landesinneren',
    'corine_411':'Sümpfe',
    'corine_412':'Torfmoore',
    'corine_420':'Feuchtflächen an der Küste',
    'corine_421':'Salzwiesen',
    'corine_422':'Salinen',
    'corine_423':'In der Gezeitenzone liegende Flächen',
    'corine_500':'Wasserflächen',
    'corine_510':'Wasserflächen im Landesinneren',
    'corine_511':'Gewässerläufe',
    'corine_512':'Wasserflächen',
    'corine_520':'Meeresgewässer',
    'corine_521':'Lagunen',
    'corine_522':'Mündungsgebiete',
    'corine_523':'Meer und Ozean',
    'land_cover': 'Bodenbedeckung',
    'land_cover_cat1': 'Bodenbedeckung (Kategorie)',
    'land_cover_cat2': 'Bodenbedeckung (Unterkategorie)',
    'link_id': 'Straße Link ID',
    'link_name': 'Straße Kurzbezeichnung',
    'link_distance': 'Straße Distanz',
    'edge_id': 'Straße Kanten ID',
    'link_name1': 'Straße Name1',
    'link_name2': 'Straße Name2',
    'link_frc': 'Straßenkategorie',
    'settlement_type': 'Dauersiedlungsraum',
    'settlement_type_1':'kein DSR',
    'settlement_type_2':'Besiedelbarer Raum',
    'settlement_type_3':'Siedlungsraum',
    'dtm_level': 'DGM-Niveau'
});