export enum ELoopEventType {
  SCHEDULE_LOOP = "SCHEDULE_LOOP",
  LOOP_SCHEDULED = "LOOP_SCHEDULED",
  TRIGGER_NEXT_TEST = "TRIGGER_NEXT_TEST",
  CANCEL_LOOP = "CANCEL_LOOP",
  LOOP_CANCELLED = "LOOP_CANCELLED",
}
