export type NetworkMeasurementType =
  | "mobile/download"
  | "mobile/upload"
  | "mobile/ping"
  | "mobile/signal"
  | "wifi/download"
  | "wifi/upload"
  | "wifi/ping"
  | "browser/download"
  | "browser/upload"
  | "browser/ping"
  | "all/download"
  | "all/upload"
  | "all/ping"
