/**
 * Translations for english Language
 * (needs to be loaded after functions.js)
 */

Lang.setStrings({
   'Mbps' : 'Mbps',
   'ms' : 'ms',
   'dBm' : 'dBm',
   'dB' : 'dB',
   'East' : 'E',
   'West' : 'W',
   'North' : 'N',
   'South' : 'S',
   'showMoreDevices' : 'Further devices',
   'AndroidAppAvailable' : 'In your mobile browser, only a simple JavaScript based test is carried out. If you would like to use the test to the full extent, please use our <a href="https://play.google.com/store/apps/details?id=at.alladin.rmbt.android&hl=en">Android-App</a>.',
   'IOSAppAvailable' : 'In your mobile browser, only a simple JavaScript based test is carried out. If you would like to use the test to the full extent, please use our <a href="https://itunes.apple.com/at/app/rtr-netztest/id724321403">iOS-App</a>.',
   'NoJavaAvailable' : 'A simple JavaScript test is carried out.',
   'BrowserOutdated' : 'Your browser version is outdated and does not support all features necessary. Please use a newer browser version.',
   'YourPostalCode' : 'Your postal code',
   'PostalCode' : 'Post code',
   'PleaseEnterPostalCode' : 'For optimum results please enter your post code.',
   'OutsideAustria' : 'Outside Austria',
   'StreetAddress' : 'Street/House number',
   'Country' : 'Country',
   'City' : 'City',
   'AddressInput' : 'optional, manual address entry',
   'PrivacyStatement' : 'Privacy statement',
   'PrivacyStatementLink' : 'https://www.rtr.at/en/tk/netztestprivacypolicy',
   'AustrianPostalCode' : 'Austrian postcode',
   'Cancel' : 'Cancel',
   'Continue' : 'Continue',
   'clickToEdit' : 'click to edit',
   'MeasurementResultFrom' : 'Measurement result from',
   'TestResult' : 'Test result',
   'YourSyncCode' : 'Your synchronisation code is',
   'History' : 'Verlauf',
   'allOperators' : 'All operators',
   'countries' : {'eu': 'Europe', 'af': 'Afghanistan', 'al': 'Albania', 'dz': 'Algeria', 'as': 'American Samoa', 'ad': 'Andorra', 'ao': 'Angola', 'ai': 'Anguilla', 'aq': 'Antarctica', 'ag': 'Antigua and Barbuda', 'ar': 'Argentina', 'am': 'Armenia', 'aw': 'Aruba', 'au': 'Australia', 'at': 'Austria', 'az': 'Azerbaijan', 'bs': 'Bahamas', 'bh': 'Bahrain', 'bd': 'Bangladesh', 'bb': 'Barbados', 'by': 'Belarus', 'be': 'Belgium', 'bz': 'Belize', 'bj': 'Benin', 'bm': 'Bermuda', 'bt': 'Bhutan', 'bo': 'Bolivia, Plurinational State of', 'bq': 'Bonaire, Sint Eustatius and Saba', 'ba': 'Bosnia and Herzegovina', 'bw': 'Botswana', 'bv': 'Bouvet Island', 'br': 'Brazil', 'io': 'British Indian Ocean Territory', 'bn': 'Brunei Darussalam', 'bg': 'Bulgaria', 'bf': 'Burkina Faso', 'bi': 'Burundi', 'kh': 'Cambodia', 'cm': 'Cameroon', 'ca': 'Canada', 'cv': 'Cape Verde', 'ky': 'Cayman Islands', 'cf': 'Central African Republic', 'td': 'Chad', 'cl': 'Chile', 'cn': 'China', 'cx': 'Christmas Island', 'cc': 'Cocos (Keeling) Islands', 'co': 'Colombia', 'km': 'Comoros', 'cg': 'Congo', 'cd': 'Congo, the Democratic Republic of the', 'ck': 'Cook Islands', 'cr': 'Costa Rica', 'ci': 'Côte d’Ivoire', 'hr': 'Croatia', 'cu': 'Cuba', 'cw': 'Curaçao', 'cy': 'Cyprus', 'cz': 'Czech Republic', 'dk': 'Denmark', 'dj': 'Djibouti', 'dm': 'Dominica', 'do': 'Dominican Republic', 'ec': 'Ecuador', 'eg': 'Egypt', 'sv': 'El Salvador', 'gq': 'Equatorial Guinea', 'er': 'Eritrea', 'ee': 'Estonia', 'et': 'Ethiopia', 'fk': 'Falkland Islands (Malvinas)', 'fo': 'Faroe Islands', 'fj': 'Fiji', 'fi': 'Finland', 'fr': 'France', 'gf': 'French Guiana', 'pf': 'French Polynesia', 'tf': 'French Southern Territories', 'ga': 'Gabon', 'gm': 'Gambia', 'ge': 'Georgia', 'de': 'Germany', 'gh': 'Ghana', 'gi': 'Gibraltar', 'gr': 'Greece', 'gl': 'Greenland', 'gd': 'Grenada', 'gp': 'Guadeloupe', 'gu': 'Guam', 'gt': 'Guatemala', 'gg': 'Guernsey', 'gn': 'Guinea', 'gw': 'Guinea-Bissau', 'gy': 'Guyana', 'ht': 'Haiti', 'hm': 'Heard Island and McDonald Islands', 'va': 'Holy See (Vatican City State)', 'hn': 'Honduras', 'hk': 'Hong Kong', 'hu': 'Hungary', 'is': 'Iceland', 'in': 'India', 'id': 'Indonesia', 'ir': 'Iran, Islamic Republic of', 'iq': 'Iraq', 'ie': 'Ireland', 'im': 'Isle of Man', 'il': 'Israel', 'it': 'Italy', 'jm': 'Jamaica', 'jp': 'Japan', 'je': 'Jersey', 'jo': 'Jordan', 'kz': 'Kazakhstan', 'ke': 'Kenya', 'ki': 'Kiribati', 'kp': 'Korea, Democratic Peoples Republic of', 'kr': 'Korea, Republic of', 'kw': 'Kuwait', 'kg': 'Kyrgyzstan', 'la': 'Lao Peoples Democratic Republic', 'lv': 'Latvia', 'lb': 'Lebanon', 'ls': 'Lesotho', 'lr': 'Liberia', 'ly': 'Libya', 'li': 'Liechtenstein', 'lt': 'Lithuania', 'lu': 'Luxembourg', 'mo': 'Macao', 'mk': 'Macedonia, The Former Yugoslav Republic of', 'mg': 'Madagascar', 'mw': 'Malawi', 'my': 'Malaysia', 'mv': 'Maldives', 'ml': 'Mali', 'mt': 'Malta', 'mh': 'Marshall Islands', 'mq': 'Martinique', 'mr': 'Mauritania', 'mu': 'Mauritius', 'yt': 'Mayotte', 'mx': 'Mexico', 'fm': 'Micronesia, Federated States of', 'md': 'Moldova, Republic of', 'mc': 'Monaco', 'mn': 'Mongolia', 'me': 'Montenegro', 'ms': 'Montserrat', 'ma': 'Morocco', 'mz': 'Mozambique', 'mm': 'Myanmar', 'na': 'Namibia', 'nr': 'Nauru', 'np': 'Nepal', 'nl': 'Netherlands', 'nc': 'New Caledonia', 'nz': 'New Zealand', 'ni': 'Nicaragua', 'ne': 'Niger', 'ng': 'Nigeria', 'nu': 'Niue', 'nf': 'Norfolk Island', 'mp': 'Northern Mariana Islands', 'no': 'Norway', 'om': 'Oman', 'pk': 'Pakistan', 'pw': 'Palau', 'ps': 'Palestine, State of', 'pa': 'Panama', 'pg': 'Papua New Guinea', 'py': 'Paraguay', 'pe': 'Peru', 'ph': 'Philippines', 'pn': 'Pitcairn', 'pl': 'Poland', 'pt': 'Portugal', 'pr': 'Puerto Rico', 'qa': 'Qatar', 're': 'Réunion', 'ro': 'Romania', 'ru': 'Russian Federation', 'rw': 'Rwanda', 'bl': 'Saint Barthélemy', 'sh': 'Saint Helena, Ascension and Tristan da Cunha', 'kn': 'Saint Kitts and Nevis', 'lc': 'Saint Lucia', 'mf': 'Saint Martin (French part)', 'pm': 'Saint Pierre and Miquelon', 'vc': 'Saint Vincent and the Grenadines', 'ws': 'Samoa', 'sm': 'San Marino', 'st': 'Sao Tome and Principe', 'sa': 'Saudi Arabia', 'sn': 'Senegal', 'rs': 'Serbia', 'sc': 'Seychelles', 'sl': 'Sierra Leone', 'sg': 'Singapore', 'sx': 'Sint Maarten (Dutch part)', 'sk': 'Slovakia', 'si': 'Slovenia', 'sb': 'Solomon Islands', 'so': 'Somalia', 'za': 'South Africa', 'gs': 'South Georgia and the South Sandwich Islands', 'ss': 'South Sudan', 'es': 'Spain', 'lk': 'Sri Lanka', 'sd': 'Sudan', 'sr': 'Suriname', 'sj': 'Svalbard and Jan Mayen', 'sz': 'Swaziland', 'se': 'Sweden', 'ch': 'Switzerland', 'sy': 'Syrian Arab Republic', 'tw': 'Taiwan, Province of China', 'tj': 'Tajikistan', 'tz': 'Tanzania, United Republic of', 'th': 'Thailand', 'tl': 'Timor-Leste', 'tg': 'Togo', 'tk': 'Tokelau', 'to': 'Tonga', 'tt': 'Trinidad and Tobago', 'tn': 'Tunisia', 'tr': 'Turkey', 'tm': 'Turkmenistan', 'tc': 'Turks and Caicos Islands', 'tv': 'Tuvalu', 'ug': 'Uganda', 'ua': 'Ukraine', 'ae': 'United Arab Emirates', 'gb': 'United Kingdom', 'us': 'United States', 'um': 'United States Minor Outlying Islands', 'uy': 'Uruguay', 'uz': 'Uzbekistan', 'vu': 'Vanuatu', 've': 'Venezuela, Bolivarian Republic of', 'vn': 'Viet Nam', 'vg': 'Virgin Islands, British', 'vi': 'Virgin Islands, U.S.', 'wf': 'Wallis and Futuna', 'eh': 'Western Sahara', 'ye': 'Yemen', 'zm': 'Zambia', 'zw': 'Zimbabwe'},
   'invalidUUID' : 'invalid UUID',
   'decimalSeperator'   : '.',
   'thousandsSeperator' : ' ',
   'implausibleResult': 'Comment: Implausible test result. Test is ignored.',
   'NDTTestFailed': 'NDT-Test failed',
   'NDTTestFinished': 'NDT-Test finished',
   'CourseOverview': 'Course overview',
   'seconds_abbreviation': 's',
   'meters_abbreviation': 'm',
   'showAdditionalInformation' : 'Show additional information ...',
   'Measurement' : 'Measurement',
   'Net' : 'Net',
   'moreInfo' : 'More Info',
   'smallView': 'small view',
   'largeView': 'large view',
   'baseLayer' : 'Base layer',
   'Skip' : 'Skip',
   
   //fields from controlserver-resource
   'time': 'Test time',
   'timezone': 'Timezone',
   'ping_shortest': 'Ping',
   'speed_upload': 'Upload speed',
   'speed_download': 'Download speed',
   'signal_strength': 'Signal strength',
   'network_type': 'Network type',
   'country_location': 'Country of location',
   'country_asn': 'Country of AS',
   'country_geoip': 'Country of IP',
   'zip_code': 'ZIP code',
   'wifi_ssid': 'WLAN SSID',
   'wifi_bssid': 'WLAN BSSID',
   'network_operator_name': 'Network (display)',
   'network_name': 'Network (display)',
   'network_operator': 'Mobile network',
   'network_sim_operator_name': 'Home network (display)',
   'network_sim_operator': 'Home network',
   'roaming': 'Roaming',
   'total_bytes': 'Data amount RMB-Test',
   'total_if_bytes': 'Data amount interface',
   'test_if_bytes_download': 'Data if_dl',
   'test_if_bytes_upload': 'Data if_ul',
   'testdl_if_bytes_download': 'Data if_dl (dl-test)',
   'testdl_if_bytes_upload': 'Data if_ul (dl-test)',
   'testul_if_bytes_download': 'Data if_dl (ul-test)',
   'testul_if_bytes_upload': 'Data if_ul (ul-test)',
   'client_name': 'Software name',
   'client_type': 'RMBT type',
   'client_version': 'RMBT version',
   'client_software_version': 'Software version',
   'plattform': 'Platform',
   'os_version': 'Platform version',
   'model': 'Model',
   'client_local_ip': 'Internal IP ',
   'client_public_ip': 'External IP',
   'client_public_ip_as_name': 'IP network name',
   'client_public_ip_as': 'IP network (name of AS)',
   'client_public_ip_rdns': 'Hostname',
   'provider_name': 'Operator',
   'nat_type': 'NAT status',
   'location': 'Location',
   'motion': 'Motion',
   'server_name': 'Testserver name',
   'server_ip': 'Testserver IP',
   'server_location_name': 'Testserver location',
   'port': 'Testserver port',
   'encryption': 'RMBT encryption',
   'encryption_false': 'No',
   'encryption_true': 'Yes',
   'duration': 'Test duration',
   'num_threads': 'Parallel connections DL',
   'num_threads_ul': 'Parallel connections UL',
   'uuid': 'Test ID',
   'open_test_uuid': 'Open Test ID',
   'time_dl_ns': 'Start time download',
   'time_ul_ns': 'Start time upload',
   'speed_download_ndt': 'Download (NDT)',
   'speed_upload_ndt': 'Upload (NDT)',
   'ping_ndt': 'Latency (NDT)',
   'ndt_details_main': 'Details NDT (main)',
   'ndt_details_stat': 'Details NDT (stat)',
   'ndt_details_diag': 'Details NDT (diag)',
   
   //values not in the controlserver resource file
   'cat_technology': 'Connection Technology',
   'country_sim': 'SIM home country',
   'platform': 'Platform',
   'ip_anonym': 'IP (anonymized)',
   'open_uuid': 'Open-User-UUID',
   'network_country': 'Country of network',
   'distance': 'Movement',
   'lte_rsrp' : 'Signal strength (RSRP)',
   'lte_rsrq' : 'Signal quality (RSRQ)',
           
    //new attributes by DZ and attributes previously not displayed
    'model_native': 'Model (native)',
    'ndt_download_kbit': 'NDT-data rate download',
    'ndt_upload_kbit': 'NDT-data rate upload',
    'time_ul_ms': 'Rel. start upload',
    'time_dl_ms': 'Rel. start download',
    'roaming_type': 'Roaming status',
    'wifi_link_speed': 'WLAN Connection Speed',
    'asn': 'AS number',
    'num_threads_requested': 'Connections requested',
    'sim_mcc_mnc': 'Home network MCC-MNC',
    'duration_download_ms': 'Download duration',
    'duration_upload_ms': 'Upload duration',
    'network_mcc_mnc': 'Mobile network MCC-MNC',
    'bytes_download': 'Data volume download',
    'bytes_upload': 'Data volume upload',
    'bytes' : 'bytes',
    'KB' : 'KB',
    'MB' : 'MB',
    'public_ip_as_name': 'IP network name',
    
    'roaming_international' : 'international roaming',
    'roaming_national' : 'national roaming',
    'roaming_none' : 'not roaming',
        
    'pleaseSelect' : 'Please select',
    'addressNotFound' : 'Address could not be found',
    
        
    //Test
    'Locating': 'Locating',
    'Initializing' : 'Initializing',
    'Init_Upload' : 'Init Upload',
    'Ping' : 'Ping',
    'Download' : 'Download',
    'Upload' : 'Upload',
    'Finished' : 'Finished',
    'Error' : 'Error',
    'Aborted' : 'Aborted',
    'ErrorOccuredDuringTest' : 'There was an error during the test.<br />Please restart!',
    'PrematureEnd' : 'Test was aborted. Please restart!',
    'AppletCouldNotBeLoaded' : 'Java Applet could not be initialized.<br />Please check your Java installation: <a href="http://www.java.com/de/download/testjava.jsp">http://www.java.com/de/download/testjava.jsp</a>',
    'ErrorOnInitializingApplet' : 'Error on initializing the applet',
    'VerlaufHash' : '/en/Verlauf#',
    'Init_applet' : 'Init applet',
    'NoPermission'  : 'No permission',
    'NotAvailable' : 'Not available',
    'NotSupported' : 'Not supported',
    'DownloadPhase' : 'Download phase',
    'UploadPhase' : 'Upload phase',
    'Successful' : 'Successful',
    'NDT' : 'NDT',
    'Failure' : 'Failure',
    'details' : 'details',
    'NoOperatorsFound' : 'No operators found for the current selection',
    'NoDevicesFound' : 'No devices found for the current selection',
    'QosTest' : 'Quality of Service',
    'FastConnectionWarning' : 'Due to technical limitations of the used test type, deviations are possible. If you suspect that the results are inaccurate, please conduct a <a href="/en/Test?Java=t">Java-based Test</a>.'
});