export enum ERoutes {
  HOME = "",
  HISTORY = "history",
  MAP = "map",
  STATISTICS = "statistics",
  TEST = "test",
  LOOP = "series-step-1",
  LOOP_2 = "series-step-2",
  LOOP_RESULT = "series-result",
  CERTIFIED = "certified-step-1",
  CERTIFIED_2 = "certified-step-2",
  CERTIFIED_3 = "certified-step-3",
  CERTIFIED_4 = "certified-step-4",
  OPEN_DATA = "opentests",
  OPTIONS = "options",
  RESULT = "result",
  TERMS = "terms-and-conditions",
  PAGE_NOT_FOUND = "page-not-found",
}
