# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CI: ""
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: |
          npm i || echo "npm audit failed, but proceeding"
      - run: npm audit
      - run: npm run ng analytics off
      - run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: build-zip
          path: dist/open-rmbt-angular/browser/
      - run: rm -r dist
      - run: npm run build:stage
      - uses: actions/upload-artifact@v4
        with:
          name: build-staging-zip
          path: dist/open-rmbt-angular/browser/
